version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: tracker78_postgres
    restart: always
    environment:
      POSTGRES_DB: Tracker78_spring
      POSTGRES_USER: Tracker_78_spring
      POSTGRES_PASSWORD: Gamersjr002$
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  spring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tracker78_spring
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Tracker78_spring
      SPRING_DATASOURCE_USERNAME: Tracker_78_spring
      SPRING_DATASOURCE_PASSWORD: Gamersjr002$
    ports:
      - "8081:8081"
    restart: always

volumes:
  pgdata: